// Drags both cards, checks clamping, persistence, minimise-in-place and reset: node tools/drag-check.mjs <outDir>
import { chromium } from 'playwright'
const out = process.argv[2]
const b = await chromium.launch({ args: ['--use-angle=d3d11', '--enable-gpu', '--ignore-gpu-blocklist'] })
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } })
const errs = []
p.on('pageerror', (e) => errs.push(e.message))
await p.goto('http://localhost:5173/?autoplay=0')
await p.evaluate(() => localStorage.setItem('buffer.introSeen', '1'))
await p.reload()
await p.waitForTimeout(2500)
const box = async (sel) => p.locator(sel).boundingBox()
const drag = async (sel, dx, dy) => {
  const g = await box(`${sel} .card-grip`)
  await p.mouse.move(g.x + g.width / 2, g.y + g.height / 2)
  await p.mouse.down()
  await p.mouse.move(g.x + g.width / 2 + dx, g.y + g.height / 2 + dy, { steps: 15 })
  await p.mouse.up()
}
const f0 = await box('section.forecast')
await drag('section.forecast', 600, -380)
const f1 = await box('section.forecast')
console.log('forecast moved by', Math.round(f1.x - f0.x), Math.round(f1.y - f0.y))
await drag('section.routing', 5000, -5000) // far past the edge: must stay on screen
const r1 = await box('section.routing')
console.log('routing clamped inside:', r1.x + r1.width <= 1920 && r1.y >= 0, Math.round(r1.x), Math.round(r1.y))
// drag by the header background too
const h = await box('section.routing header')
await p.mouse.move(h.x + 40, h.y + 6)
await p.mouse.down()
await p.mouse.move(h.x - 260, h.y + 200, { steps: 12 })
await p.mouse.up()
const r2 = await box('section.routing')
console.log('routing moved by header:', Math.round(r2.x - r1.x), Math.round(r2.y - r1.y))
await p.screenshot({ path: `${out}/dragged.png` })
await p.reload()
await p.waitForTimeout(2500)
const f2 = await box('section.forecast')
console.log('position remembered after reload:', Math.abs(f2.x - f1.x) < 2 && Math.abs(f2.y - f1.y) < 2)
await p.getByRole('button', { name: 'Minimise Forecast and evidence' }).click()
await p.waitForTimeout(500)
const fab = await box('.card-fab.forecast')
console.log('circle sits where the card was:', Math.abs(fab.x - f2.x) < 40, Math.round(fab.x), Math.round(fab.y))
await p.getByRole('button', { name: 'Open Forecast and evidence' }).click({ force: true })
await p.waitForTimeout(500)
await p.locator('section.forecast .card-grip').dblclick()
await p.waitForTimeout(300)
const f3 = await box('section.forecast')
console.log('double-click resets:', Math.abs(f3.x - f0.x) < 2 && Math.abs(f3.y - f0.y) < 2)
console.log('page errors:', errs)
await p.evaluate(() => Object.keys(localStorage).filter((k) => k.startsWith('buffer.card')).forEach((k) => localStorage.removeItem(k)))
await b.close()
